export const taglines = [
  "Code whispers. I listen.",
  "Between the lines is where I live.",
  "Every line tells a story.",
  "What's not said is everything.",
  "Reading the world. Writing the future.",
  "I translate human into digital.",
  "Stories in syntax. Narratives in code.",
  "Where elegant code meets human need.",
  "Code with purpose. Design with soul.",
  "Where elegant code meets human need.",
  "Building tomorrow's experiences today.",
  "Craft. Code. Create.",
  "Engineering beauty into every pixel.",
  "Simplicity is the ultimate sophistication.",
  "Code that thinks. Design that feels.",
  "Where art meets algorithm.",
  "Obsessed with the details you'll never see.",
  "Making the complex beautifully simple.",
  "Solving problems you didn't know you had.",
  "Code what users need, not what they ask for.",
  "Finding elegance in the unspoken.",
  "Building what's missing, not what's obvious.",
  "Reading between the pixels.",
  "Anticipating the need before the ask.",
  "Where intuition meets implementation.",
  "Crafting solutions for silent problems.",
  "Decoding what users really want.",
  "Engineering empathy into every interaction.",
  "Seeing the unseen. Building the unbuilt.",
];
